lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
# token extraction settings
    token_extractors:
        # check token in a cookie
        cookie:
            enabled: true
            name: BEARER
    # ...
    set_cookies:
        BEARER: ~